// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/muhsatrio/golang-boilerplate/platform/jwt (interfaces: JwtAdapter)

// Package mock_jwt is a generated GoMock package.
package mock_jwt

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/muhsatrio/golang-boilerplate/domain"
)

// MockJwtAdapter is a mock of JwtAdapter interface.
type MockJwtAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockJwtAdapterMockRecorder
}

// MockJwtAdapterMockRecorder is the mock recorder for MockJwtAdapter.
type MockJwtAdapterMockRecorder struct {
	mock *MockJwtAdapter
}

// NewMockJwtAdapter creates a new mock instance.
func NewMockJwtAdapter(ctrl *gomock.Controller) *MockJwtAdapter {
	mock := &MockJwtAdapter{ctrl: ctrl}
	mock.recorder = &MockJwtAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtAdapter) EXPECT() *MockJwtAdapterMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockJwtAdapter) GenerateToken(arg0 domain.TokenClaim) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockJwtAdapterMockRecorder) GenerateToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockJwtAdapter)(nil).GenerateToken), arg0)
}
